"""add paragraph sequence index and reviewed documents table

Revision ID: 49773ead174a
Revises: b7f1d023970c
Create Date: 2026-07-23 05:07:25.474296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49773ead174a'
down_revision: Union[str, None] = 'b7f1d023970c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewed_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('highlight_count', sa.Integer(), nullable=False),
    sa.Column('tracked_change_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document_paragraphs', sa.Column('sequence_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_paragraphs', 'sequence_index')
    op.drop_table('reviewed_documents')
    # ### end Alembic commands ###
