"""add document processing tables

Revision ID: b1731776ab1e
Revises: 
Create Date: 2026-07-21 19:09:54.274284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b1731776ab1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('paragraph_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('start_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('col_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_paragraphs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('paragraph_type', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('col_index', sa.Integer(), nullable=True),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('list_level', sa.Integer(), nullable=True),
    sa.Column('style_name', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('runs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['document_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_paragraphs')
    op.drop_table('document_tables')
    op.drop_table('document_sections')
    op.drop_table('documents')
    # ### end Alembic commands ###
